---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - TYPEORM_HOST: ${TYPEORM_HOST}
    - TYPEORM_PORT: ${TYPEORM_PORT}
    - TYPEORM_USERNAME: ${TYPEORM_USERNAME}
    - TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
    - TYPEORM_DATABASE: ${TYPEORM_DATABASE}

  roles:
    - deploy
