---

- name: Download nodejs
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

- name: update cache
  become: yes
  apt:
    update_cache: yes

- name: install nodejs
  become: yes
  apt: 
    name: nodejs
    state: present

- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes