---

- name: Download nodejs
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

- name: update cache
  become: yes
  apt:
    update_cache: yes

- name: install nodejs
  become: yes
  apt: 
    name: nodejs
    state: present

- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: create user pm2
  become: yes
  user:
    name: pm2
    shell: /bin/bash
    password: pm21
    groups: sudo
    append: yes

- name: allow using port 80 for non root
  become: yes
  shell: |
    apt-get install libcap2-bin
    setcap cap_net_bind_service=+ep /usr/bin/node

- name: create udapeople dir
  become: yes
  file:
    path: /home/pm2/udapeople
    state: directory
    owner: pm2
    group: pm2
    mode: 0775
