## Copy backend files from circleci docker container to server
---

- name: untar backend on remote
  become: yes
  unarchive:
    src: /root/project/backend/dist.tgz
    dest: /home/pm2/udapeople
    owner: pm2
    group: pm2

- name: run js app
  become_user: pm2
  shell: 
    chdir: /home/pm2/udapeople/dist
    cmd: pm2 start main.js

    

  
