## Copy backend files from circleci docker container to server
---

- name: untar backend on remote
  become: yes
  unarchive:
    src: /root/project/backend.tgz
    dest: /home/pm2/udapeople
    owner: pm2
    group: pm2

- name: run js app
  become: yes
  become_user: pm2
  shell: 
    chdir: /home/pm2/udapeople/backend
    cmd: pm2 start npm --name backend -- start
  environment:
    ENVIRONMENT: production
    TYPEORM_HOST: udapeople.cvoqi16sdmf6.eu-west-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: udaAdmin
    TYPEORM_PASSWORD: udaAdmin
    TYPEORM_DATABASE: udapeople
  #pm2 start main.js

    

  
