## Copy backend files from circleci docker container to server
---
- name: create app dir
  file:
    path: ~/udapeople
    state: directory

- name: copy files
  copy:
    src: /home/circleci/project/backend/dist/
    dest: ~/udapeople
    owner: ubuntu
    group: ubuntu
    force: no