## Copy backend files from circleci docker container to server
---
- name: tar backend locally
  archive:
    path: /root/project/backend/dist
    dest: /root/project/backend/dist.tgz
    delegate_to: localhost

- name: untar backend on remote
  unarchive:
    src: /root/project/backend/dist.tgz
    dest: ~/udapeople
    owner: ubuntu
    group: ubuntu
    #remote_src: yes

#- name: copy files
#  become: yes
#  copy:
#    src: /root/project/backend/dist
#    dest: ~/udapeople
#    owner: ubuntu
#    group: ubuntu
#    force: yes