## Copy backend files from circleci docker container to server
---
#- name: create app dir
#  file:
#    path: ~/udapeople
#    state: directory

- name: copy files
  become: yes
  copy:
    src: $(pwd)
    dest: ~/udapeople
    owner: ubuntu
    group: ubuntu
    force: yes