## Copy backend files from circleci docker container to server
---

- name: create user pm2
  become: yes
  user:
    name: pm2
    shell: /bin/bash
    password: pm21
    groups: sudo
    append: yes

- name: untar backend on remote
  unarchive:
    src: /root/project/backend/dist.tgz
    dest: /home/pm2/udapeople
    owner: pm2
    group: pm2

- name: allow using port 80 for non root
  become: yes
  shell: |
    sudo apt-get install libcap2-bin
    sudo setcap cap_net_bind_service=+ep /usr/local/bin/node

- name: run js app
  shell: 
    chdir: /home/pm2/udapeople/backend
    cmd: pm2 start webpack.config.js

    

  
